-- begin ADMINTOOLSDEMO_CONTRACT
alter table ADMINTOOLSDEMO_CONTRACT add constraint FK_ADMINTOOLSDEMO_CONTRACT_ON_CONTRACTOR foreign key (CONTRACTOR_ID) references ADMINTOOLSDEMO_CONTRACTOR(ID)^
create index IDX_ADMINTOOLSDEMO_CONTRACT_ON_CONTRACTOR on ADMINTOOLSDEMO_CONTRACT (CONTRACTOR_ID)^
-- end ADMINTOOLSDEMO_CONTRACT
